CREATE TABLE IF NOT EXISTS admins (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL,
 email VARCHAR(254) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS admin_sessions (
 token_hash CHAR(64) PRIMARY KEY, admin_id INT UNSIGNED NOT NULL, expires_at DATETIME NOT NULL,
 FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE, INDEX(expires_at)
);
CREATE TABLE IF NOT EXISTS rate_limits (
 bucket CHAR(64) PRIMARY KEY, attempts INT NOT NULL DEFAULT 1, expires_at DATETIME NOT NULL, INDEX(expires_at)
);
CREATE TABLE IF NOT EXISTS homepage_sections (
 slug VARCHAR(100) PRIMARY KEY, content JSON NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS portfolio_categories (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, slug VARCHAR(180) NOT NULL UNIQUE,
 description TEXT NOT NULL, status ENUM('active','inactive') NOT NULL DEFAULT 'active',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS portfolio_projects (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id INT UNSIGNED NOT NULL, name VARCHAR(200) NOT NULL,
 slug VARCHAR(220) NOT NULL UNIQUE, status ENUM('draft','published') NOT NULL DEFAULT 'draft', featured BOOLEAN NOT NULL DEFAULT FALSE,
 content JSON NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(category_id) REFERENCES portfolio_categories(id), INDEX(status,featured), INDEX(category_id)
);
CREATE TABLE IF NOT EXISTS portfolio_project_images (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, project_id INT UNSIGNED NOT NULL, url VARCHAR(1000) NOT NULL,
 alt_text VARCHAR(255) NOT NULL DEFAULT '', sort_order INT NOT NULL DEFAULT 0,
 FOREIGN KEY(project_id) REFERENCES portfolio_projects(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS blog_categories (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, slug VARCHAR(180) NOT NULL UNIQUE,
 description TEXT NOT NULL, status ENUM('active','inactive') NOT NULL DEFAULT 'active',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS blog_posts (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id INT UNSIGNED NOT NULL, title VARCHAR(250) NOT NULL,
 slug VARCHAR(220) NOT NULL UNIQUE, status ENUM('draft','published') NOT NULL DEFAULT 'draft', publish_date DATE NOT NULL,
 content JSON NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(category_id) REFERENCES blog_categories(id), INDEX(status,publish_date), INDEX(category_id)
);
CREATE TABLE IF NOT EXISTS contact_enquiries (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(254) NOT NULL,
 phone VARCHAR(30) NOT NULL, company VARCHAR(160) NOT NULL, service VARCHAR(160) NOT NULL, budget VARCHAR(160) NOT NULL,
 message TEXT NOT NULL, status ENUM('new','contacted','closed') NOT NULL DEFAULT 'new',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(status,created_at)
);
CREATE TABLE IF NOT EXISTS website_settings (
 id INT PRIMARY KEY, content JSON NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS media (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, filename VARCHAR(255) NOT NULL UNIQUE, path VARCHAR(1000) NOT NULL,
 url VARCHAR(1000) NOT NULL, alt_text VARCHAR(255) NOT NULL DEFAULT '', mime_type VARCHAR(100) NOT NULL, size INT UNSIGNED NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
