/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as UploadsSplatRouteImport } from './routes/uploads.$'
import { Route as ApiCmsSplatRouteImport } from './routes/api.cms.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsSplatRoute = ApiCmsSplatRouteImport.update({
  id: '/api/cms/$',
  path: '/api/cms/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/cms/$': typeof ApiCmsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/cms/$': typeof ApiCmsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/cms/$': typeof ApiCmsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/admin/$'
    | '/admin/login'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/uploads/$'
    | '/admin/'
    | '/blog/'
    | '/portfolio/'
    | '/services/'
    | '/api/cms/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/admin/$'
    | '/admin/login'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/uploads/$'
    | '/admin'
    | '/blog'
    | '/portfolio'
    | '/services'
    | '/api/cms/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/admin/$'
    | '/admin/login'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/uploads/$'
    | '/admin/'
    | '/blog/'
    | '/portfolio/'
    | '/services/'
    | '/api/cms/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiCmsSplatRoute: typeof ApiCmsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/$': {
      id: '/api/cms/$'
      path: '/api/cms/$'
      fullPath: '/api/cms/$'
      preLoaderRoute: typeof ApiCmsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiCmsSplatRoute: ApiCmsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
